language: cpp

before_install:
  - export DISTRO=`lsb_release -a 2>/dev/null | grep Codename | awk '{ print $2 }'`
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common || sudo apt-get install python-software-properties || true
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:mapnik/boost
  - sudo apt-add-repository -y ppa:jbboehr/ppa
  - sudo apt-add-repository -y ppa:jbboehr/handlebars
  - sudo apt-add-repository -y ppa:mandel/movie-tracker
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
  - echo deb http://dl.hhvm.com/ubuntu $DISTRO main | sudo tee /etc/apt/sources.list.d/hhvm.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhandlebars-dev libtalloc-dev hhvm hhvm-dev g++-4.8 gcc-4.8 libboost1.49-dev libgoogle-glog-dev libjemalloc-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20 || true
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20 || true
  - sudo update-alternatives --config gcc || true
  - sudo update-alternatives --config g++ || true
  - export CXX=`which g++-4.8`
  - export CC=`which gcc-4.8`
  - '[ -z "`which phpunit`" ] && wget https://phar.phpunit.de/phpunit.phar && chmod +x phpunit.phar && sudo mv phpunit.phar /usr/local/bin/phpunit'

script:
  - hphpize
  - cmake .
  - make
  - php generate-tests.php
  - ./test

branches:
  only:
    - master

