language: php

php:
  - hhvm

before_install:
# thanks, rabbitmq
  - ls /etc/apt/sources.list.d/ || true
  - cat /etc/apt/sources.list || true
  - sudo rm -f /etc/apt/sources.list.d/*rabbit*
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common || sudo apt-get install python-software-properties || true
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:jbboehr/ppa
  - sudo apt-add-repository -y ppa:jbboehr/handlebars
  - sudo apt-add-repository -y ppa:mandel/movie-tracker
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhandlebars-dev libtalloc-dev hhvm hhvm-dev g++-4.8 gcc-4.8 libboost1.49-dev libgoogle-glog-dev libjemalloc-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - hphpize
  - cmake .
  - make
  - sudo make install
  - 'sudo echo "hhvm.dynamic_extension_path=`pwd`" >> /etc/hhvm/php.ini'
  - 'sudo echo "hhvm.dynamic_extensions[handlebars]=handlebars.so" >> /etc/hhvm/php.ini'
  - php generate-tests.php

script:
  - phpunit ./tests

branches:
  only:
    - master
    - travisci-changes

