language: php

php:
  - hhvm

branches:
  only:
    - master

sudo: required

before_install:
  - travis_retry ./.travis.sh before_install

install:
  - travis_retry ./.travis.sh install

before_script:
  - travis_retry ./.travis.sh before_script

script:
  - phpunit ./tests

